#define ADDMSGARROW 213
#define SHOWMSGARROW 214
#define MOVECUSTOM 215
#define TRUNCATE 216
#define XSHAPE_ADDPT 217
#define XSHAPE_MOVEPT 218
#define ADDPTS 219
#define xdraw_CENTER 0
#define xdraw_ZOOM 1
#define xdraw_VIEWPOINT 2
#define xgraph_PLOT 0
#define xgraph_PLOTSCALE 1
#define xgraph_X 2
#define xgraph_WAVEPLOT 3
#define xshape_PATH 0
#define xplot_PLOT 0
#define xplot_PLOTSCALE 1
#define xplot_X 2
#define xplot_WAVEPLOT 3
#define xcell_COLOR 0
#define xcell_DIAMETER 1
#define xcell_POSITION 2
#define xcell_COLDIA 3
#define xcell_COLDIAPOS 4
#define xvar_VAL1 0
#define xvar_VAL2 1
#define xvar_VAL3 2
#define xvar_VAL4 3
#define xvar_VAL5 4
#define xview_VAL1 0
#define xview_VAL2 1
#define xview_VAL3 2
#define xview_VAL4 3
#define xview_VAL5 4
#define xview_COORDS 5
#define xview_IVAL1 6
#define xview_IVAL2 7
#define xview_IVAL3 8
#define xview_IVAL4 9
#define xview_IVAL5 10
#define xview_ICOORDS 11
