#define TO_XTEXT 225
#define FROM_XTEXT 226
#define LOAD 227
#define pool_REAC 0
#define pool_MM_PRD 1
#define pool_SLAVE 2
#define pool_REMAINING 3
#define pool_CONSERVE 4
#define pool_VOL 5
#define pool_SUMTOTAL 6
#define pool_MIRROR 7
#define reac_SUBSTRATE 0
#define reac_PRODUCT 1
#define reac_KF 2
#define reac_KB 3
#define enz_ENZYME 0
#define enz_SUBSTRATE 1
#define enz_VOL 2
#define enz_INTRAMOL 3
#define concchan_SUBSTRATE 0
#define concchan_PRODUCT 1
#define concchan_NUMCHAN 2
#define concchan_Vm 3
