#define channelA_VOLTAGE 0
#define channelA_ACTIVATION 1
#define channelB_VOLTAGE 0
#define channelB_ACTIVATION 1
#define channelC_ACTIVATION 0
#define channelC_RAND_ACTIVATION 1
#define channelC2_VOLTAGE 0
#define channelC2_ACTIVATION 1
#define channelC2_RAND_ACTIVATION 2
#define channelC3_VOLTAGE 0
#define channelC3_ACTIVATION 1
#define manuelconduct_VOLTAGE 0
#define manuelconduct_ACTIVATION 1
#define manuelconduct_RAND_ACTIVATION 2
#define Ca_concen_I_Ca 0
#define Ca_concen_fI_Ca 1
#define Ca_concen_INCREASE 2
#define Ca_concen_DECREASE 3
#define Ca_concen_BASE 4
#define Mg_block_VOLTAGE 0
#define Mg_block_CHANNEL1 1
#define Mg_block_CHANNEL2 2
#define Mg_block_CHANNEL 2
#define Mg_block_CHARGE 3
#define leakage_VOLTAGE 0
#define compartment_CHANNEL 0
#define compartment_RAXIAL 1
#define compartment_AXIAL 2
#define compartment_INJECT 3
#define compartment_EREST 6
#define symcompartment_CHANNEL 0
#define symcompartment_RAXIAL 1
#define symcompartment_RAXIAL2 2
#define symcompartment_AXIAL 2
#define symcompartment_CONNECTTAIL 1
#define symcompartment_CONNECTHEAD 2
#define symcompartment_INJECT 3
#define symcompartment_CONNECTCROSS 5
#define symcompartment_EREST 6
#define unit_INJECT 0
#define RC_INJECT 0
#define site_ACTIVATION 1
#define ghk_Cin 0
#define ghk_CIN 0
#define ghk_Cout 1
#define ghk_COUT 1
#define ghk_VOLTAGE 3
#define ghk_PERMEABILITY 4
#define izcell_CHANNEL 1
#define izcell_INJECT 0
