#define diffamp_PLUS 0
#define diffamp_MINUS 1
#define diffamp_GAIN 2
#define efield_CURRENT 0
#define expthresh_BUFFER 0
#define freq_monitor_NONZERO_TRIG 0
#define freq_monitor_ZERO_TRIG 1
#define freq_monitor_POSITIVE_TRIG 2
#define freq_monitor_NEGATIVE_TRIG 3
#define freq_monitor_WINDOW 4
#define freq_monitor_CONTINUOUS 5
#define nernst_CIN 0
#define nernst_COUT 1
#define nernst_TEMP 2
#define funcgen_AMPLITUDE 0
#define funcgen_DC_OFFSET 1
#define funcgen_PHASE 2
#define funcgen_FREQUENCY 3
#define peristim_INVM 0
#define peristim_TRIGGER 1
#define peristim_READTIME 2
#define peristim_INSPIKE 3
#define interspike_INPUT 0
#define interspike_TRIGGER 1
#define interspike_SPIKE 2
#define TABCREATE 200
#define TABFILL 201
#define TUPDATE 250
#define OPEN 300
#define CLOSE 301
#define FLUSH 302
#define crosscorr_YSPIKE 1
#define crosscorr_XSPIKE 0
#define autocorr_SPIKE 0
#define event_tofile_INPUT 0
#define calculator_SUM 0
#define calculator_SUBTRACT 1
#define calculator_MULTIPLY 2
#define calculator_DIVIDE 3
