
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int yylineno;

int yylineno = 1;

extern char yytext[];

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng + (yy_more_offset) >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( &yytext[(yy_more_offset)], (yytext_ptr), yyleng + 1 ); \
	yyleng += (yy_more_offset); \
	(yy_prev_more_offset) = (yy_more_offset); \
	(yy_more_offset) = 0; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 49
#define YY_END_OF_BUFFER 50
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[915] =
    {   0,
        1,    1,   50,   48,   49,   17,   48,   49,    9,   49,
       48,   49,   12,   48,   49,   48,   49,   48,   49,   48,
       49,   48,   49,   48,   49,   42,   48,   49,   33,   48,
       49,   48,   49,   35,   48,   49,   41,   48,   49,   11,
       48,   49,   41,   48,   49,   41,   48,   49,   41,   48,
       49,   41,   48,   49,   41,   48,   49,   41,   48,   49,
       41,   48,   49,   46,   48,   49,   48,   49,   47,   48,
       49,   15,   48,   49,   16,   17,   48,   49,    7,    9,
       49,   15,   48,   49,   15,   48,   49,   15,   48,   49,
       15,   48,   49,   15,   48,   49,   15,   42,   48,   49,

       15,   33,   48,   49,   15,   48,   49,   15,   35,   48,
       49,   15,   41,   48,   49,   15,   41,   48,   49,   15,
       41,   48,   49,   15,   41,   48,   49,   15,   41,   48,
       49,   15,   41,   48,   49,   15,   41,   48,   49,   15,
       41,   48,   49,   15,   48,   49,   14,   48,   49,   14,
       48,   49,   14,   48,   49,   14,   48,   49,   14,   48,
       49,   14,   48,   49,   14,   42,   48,   49,   14,   33,
       48,   49,   14,   48,   49,   14,   35,   48,   49,   14,
       41,   48,   49,   14,   41,   48,   49,   14,   41,   48,
       49,   14,   41,   48,   49,   14,   41,   48,   49,   14,

       41,   48,   49,   14,   41,   48,   49,   14,   41,   48,
       49,   14,   48,   49,    1,   48,   49,    1,   17,   48,
       49,    3,    9,   49,    1,   48,   49,    1,   12,   48,
       49,    1,   48,   49,    1,   48,   49,    2,   48,   49,
        1,   48,   49,    1,   48,   49,    1,   42,   48,   49,
        1,   33,   48,   49,    1,   48,   49,    1,   35,   48,
       49,    1,   41,   48,   49,    1,   11,   48,   49,    1,
       41,   48,   49,    1,   41,   48,   49,    1,   41,   48,
       49,    1,   41,   48,   49,    1,   41,   48,   49,    1,
       41,   48,   49,    1,   41,   48,   49,    1,   46,   48,

       49,    1,   48,   49,    1,   47,   48,   49,   17,   38,
       12,   13,   40,   45,    5,    6,   44,   42,   34,   37,
       36,   41,   11,   41,   41,   41,   41,   41,   41,   41,
       23,   41,   41,   41,   41,   41,   39,   15,   16,   17,
       15,   38,   15,   40,   15,   15,   45,    5,   15,    6,
       15,   15,   44,   15,   42,   15,   15,   34,   15,   37,
       15,   36,   15,   41,   15,   41,   15,   41,   15,   41,
       15,   41,   15,   41,   15,   41,   15,   41,   15,   23,
       41,   15,   41,   15,   41,   15,   41,   15,   41,   15,
       39,   14,   14,   38,   14,   40,   14,   14,   45,    5,

       14,    6,   14,   14,   44,   14,   42,   14,   14,   34,
       14,   37,   14,   36,   14,   41,   14,   41,   14,   41,
       14,   41,   14,   41,   14,   41,   14,   41,   14,   41,
       14,   23,   41,   14,   41,   14,   41,   14,   41,   14,
       41,   14,   39,    1,    1,   17,    1,   38,    1,   12,
        1,   13,    1,   40,    4,    1,   45,    1,    6,    1,
       44,    1,   42,    1,    1,   34,    1,   37,    1,   36,
        1,   41,    1,   11,    1,   41,    1,   41,    1,   41,
        1,   41,    1,   41,    1,   41,    1,   41,    1,   23,
       41,    1,   41,    1,   41,    1,   41,    1,   41,    1,

       39,    6,   10,   44,   45,   43,   41,   41,   27,   41,
       41,   41,   25,   41,   41,   41,   30,   41,   41,   32,
       41,   41,   15,   15,    6,   15,    8,   10,   15,   44,
       45,   15,   15,   15,   43,   15,   41,   15,   41,   15,
       27,   41,   15,   41,   15,   41,   15,   25,   41,   15,
       41,   15,   41,   15,   30,   41,   15,   41,   15,   32,
       41,   15,   41,   14,   14,    6,   14,   14,   44,   45,
       14,   14,   14,   43,   14,   41,   14,   41,   14,   27,
       41,   14,   41,   14,   41,   14,   25,   41,   14,   41,
       14,   41,   14,   30,   41,   14,   41,   14,   32,   41,

       14,   41,    1,    1,    6,    1,   44,   45,    1,    1,
        1,   43,    1,   41,    1,   41,    1,   27,   41,    1,
       41,    1,   41,    1,   25,   41,    1,   41,    1,   41,
        1,   30,   41,    1,   41,    1,   32,   41,    1,   41,
       45,   44,   41,   24,   41,   41,   41,   41,   41,   41,
       41,   41,   15,   15,   15,   45,   15,   15,   15,   44,
       15,   41,   15,   24,   41,   15,   41,   15,   41,   15,
       41,   15,   41,   15,   41,   15,   41,   15,   41,   14,
       14,   14,   45,   14,   14,   14,   44,   14,   41,   14,
       24,   41,   14,   41,   14,   41,   14,   41,   14,   41,

       14,   41,   14,   41,   14,   41,    1,    1,   45,    1,
        1,    1,   44,    1,   41,    1,   24,   41,    1,   41,
        1,   41,    1,   41,    1,   41,    1,   41,    1,   41,
        1,   41,   44,   45,   20,   41,   41,   31,   41,   41,
       41,   41,   41,   22,   41,   15,   15,   15,   44,   45,
       15,   20,   41,   15,   41,   15,   31,   41,   15,   41,
       15,   41,   15,   41,   15,   41,   15,   22,   41,   14,
       14,   14,   44,   45,   14,   20,   41,   14,   41,   14,
       31,   41,   14,   41,   14,   41,   14,   41,   14,   41,
       14,   22,   41,    1,    1,   44,   45,    1,   20,   41,

        1,   41,    1,   31,   41,    1,   41,    1,   41,    1,
       41,    1,   41,    1,   22,   41,   29,   41,   41,   41,
       41,   21,   41,   15,   15,   29,   41,   15,   41,   15,
       41,   15,   41,   15,   21,   41,   14,   14,   29,   41,
       14,   41,   14,   41,   14,   41,   14,   21,   41,    1,
       29,   41,    1,   41,    1,   41,    1,   41,    1,   21,
       41,   26,   41,   41,   18,   41,   15,   15,   26,   41,
       15,   41,   15,   18,   41,   14,   14,   26,   41,   14,
       41,   14,   18,   41,    1,   26,   41,    1,   41,    1,
       18,   41,   28,   41,   15,   15,   28,   41,   14,   14,

       28,   41,    1,   28,   41,   15,   14,   15,   14,   19,
       15,   19,   14,   19
    } ;

static yyconst flex_int16_t yy_accept[454] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    3,    3,
        3,    4,    6,    9,   11,   13,   16,   18,   20,   22,
       24,   26,   29,   32,   34,   37,   40,   43,   46,   49,
       52,   55,   58,   61,   64,   67,   69,   72,   75,   79,
       82,   85,   88,   91,   94,   97,  101,  105,  108,  112,
      116,  120,  124,  128,  132,  136,  140,  144,  147,  150,
      153,  156,  159,  162,  165,  169,  173,  176,  180,  184,
      188,  192,  196,  200,  204,  208,  212,  215,  218,  222,
      225,  228,  232,  235,  238,  241,  244,  247,  251,  255,
      258,  262,  266,  270,  274,  278,  282,  286,  290,  294,

      298,  302,  305,  309,  310,  311,  312,  313,  314,  314,
      315,  316,  317,  318,  319,  319,  320,  321,  322,  323,
      324,  325,  326,  327,  328,  329,  330,  331,  333,  334,
      335,  336,  337,  338,  339,  341,  343,  345,  346,  348,
      350,  352,  354,  356,  357,  359,  361,  363,  365,  367,
      369,  371,  373,  375,  377,  379,  382,  384,  386,  388,
      390,  392,  393,  395,  397,  398,  400,  402,  404,  406,
      408,  409,  411,  413,  415,  417,  419,  421,  423,  425,
      427,  429,  431,  434,  436,  438,  440,  442,  444,  445,
      447,  449,  451,  453,  455,  456,  458,  460,  462,  464,

      465,  467,  469,  471,  473,  475,  477,  479,  481,  483,
      485,  487,  489,  492,  494,  496,  498,  500,  502,  502,
      502,  503,  504,  506,  506,  506,  507,  508,  509,  511,
      512,  513,  515,  516,  517,  519,  520,  522,  523,  524,
      525,  527,  529,  532,  533,  534,  536,  538,  540,  543,
      545,  547,  550,  552,  554,  557,  559,  562,  564,  565,
      566,  568,  571,  572,  573,  575,  577,  579,  582,  584,
      586,  589,  591,  593,  596,  598,  601,  603,  604,  606,
      609,  610,  611,  613,  615,  617,  620,  622,  624,  627,
      629,  631,  634,  636,  639,  641,  641,  641,  642,  642,

      642,  643,  644,  646,  647,  648,  649,  650,  651,  652,
      653,  654,  655,  657,  658,  659,  661,  663,  666,  668,
      670,  672,  674,  676,  678,  680,  681,  682,  684,  685,
      686,  688,  690,  693,  695,  697,  699,  701,  703,  705,
      707,  708,  710,  711,  712,  714,  716,  719,  721,  723,
      725,  727,  729,  731,  733,  733,  733,  735,  737,  738,
      740,  741,  742,  743,  744,  746,  747,  748,  751,  754,
      756,  759,  761,  763,  765,  767,  770,  771,  772,  775,
      778,  780,  783,  785,  787,  789,  791,  794,  795,  798,
      801,  803,  806,  808,  810,  812,  814,  817,  817,  819,

      820,  821,  822,  824,  825,  828,  830,  832,  834,  837,
      838,  841,  843,  845,  847,  850,  853,  855,  857,  859,
      862,  862,  864,  865,  867,  868,  871,  873,  876,  877,
      880,  882,  885,  888,  890,  893,  893,  895,  896,  899,
      900,  903,  906,  906,  907,  908,  908,  909,  910,  911,
      913,  915,  915
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    1,    7,    1,    8,
        8,    9,   10,    8,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    1,   15,   16,
       17,   18,    1,    1,   19,   19,   20,   21,   22,   19,
       19,   19,   23,   19,   19,   19,   19,   24,   19,   25,
       19,   26,   27,   28,   19,   19,   19,   19,   19,   19,
        1,   29,    1,    1,   19,    1,   30,   31,   32,   33,

       34,   35,   19,   36,   37,   19,   38,   39,   19,   40,
       41,   19,   19,   42,   43,   44,   45,   19,   46,   47,
       19,   19,   48,   49,   50,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[51] =
    {   0,
        1,    2,    3,    1,    4,    2,    1,    5,    6,    1,
        1,    1,    1,    7,    8,    1,    1,    1,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    2,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    2,    1,    2
    } ;

static yyconst flex_int16_t yy_base[468] =
    {   0,
        0,    0,   50,    0,  100,    0,  150,    0,    0,    0,
     1008, 1009, 1005, 1009,  989,    0,  991,  997,  981,  988,
      192,  190,  984,  983,  982,    0,    0,  956,  167,  170,
      168,  963,  952,  959, 1009,  945, 1009,    0,  991, 1009,
      975,  984,  968,  975,  204,  204,  971,  970,  969,  238,
      287,  180,  189,  201,  187,  181,  216,  936,    0,  967,
      976,  960,  967,  224,  245,  963,  962,  961,  336,  385,
      221,  230,  238,  198,  220,  234,  928,    0,  974, 1009,
      958,  272,  960,  966,  222,  958,  273,  294,  954,  953,
      952,  434,  959,  484,  270,  279,  250,  232,  269,  247,

        0,  918,    0,  964, 1009,    0,  951, 1009,  940,  293,
     1009,  960,  300,  343,  321, 1009, 1009, 1009,    0,    0,
      928,  918,  927,  915,  917,  915,  916,    0,  221,  911,
      912,  916, 1009,    0,  950,    0,    0,  927,  316,    0,
      533,  342,  346,  352,    0,    0,    0,  908,  259,  283,
      300,  297,  328,  907,  319,  906,  339,  330,  905,  336,
        0,    0,    0,    0,  922,  353,    0,  582,  377,  392,
      398,    0,    0,    0,  903,  348,  373,  346,  363,  376,
      902,  379,  901,  378,  381,  900,  387,    0,    0,  939,
        0,  314,  926,    0, 1009,  434,  428,  439,  443,  448,

        0,    0,    0,  897,  929,  430,  390,  351,  386,  425,
      895,  429,  894,  461,  432,  893,  433,    0,  913,  496,
      930, 1009,  490,  504,  918,  917,  900,  895,    0,  894,
      897,  892,  893,  885,    0,  878,    0,  883,  900,  506,
      631, 1009,  497,  511,  906,  905,  498,  445,  876,  495,
      500,  507,  466,  439,  875,  501,  874,  505,  894,  540,
      680,  531,  545,  900,  899,  522,  524,  870,  526,  527,
      529,  535,  531,  869,  530,  868,  537,  581,  451,  560,
      586,  895,  894,  556,  559,  865,  565,  572,  570,  571,
      566,  864,  564,  863,  576,  877,  889,  888,  606,  887,

      886,  861,    0,  856,  853,  866,  851,  849,  851,  858,
      864,  876,  875,  611,  874,  873,  485,  844,  843,  536,
      589,  582,  593,  842,  605,  856,  868,  867,  630,  866,
      865,  585,  836,  835,  601,  612,  606,  607,  834,  617,
      861,  860,  647,  859,  858,  624,  829,  828,  611,  626,
      621,  622,  827,  635,  848,  853,  852,    0,  825,    0,
      832,  826,  829,  821,    0,  840,  845,  844,  815,  630,
      814,  642,  634,  645,  633,  813,  834,  839,  838,  809,
      649,  808,  648,  655,  660,  654,  807,  834,  833,  804,
      658,  803,  663,  662,  668,  666,  765,  776,    0,  763,

      750,  752,    0,  757,  735,  671,  587,  669,  734,  749,
      732,  676,  673,  682,  727,  726,  681,  678,  687,  725,
      743,    0,  721,    0,  737,  717,  685,  712,  730,  710,
      691,  703,  696,  692,  695,  701,    0,  697,  568,  564,
      519,  467,  452,  415,  385,  335,  293,  275, 1009,    0,
        0, 1009,  734,  203,  742,  750,  757,  764,  772,  780,
      788,  796,  804,  812,  820,  828,  836
    } ;

static yyconst flex_int16_t yy_def[468] =
    {   0,
      452,    1,  452,    3,  452,    5,  452,    7,    1,    1,
      452,  452,  452,  452,  452,  453,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  454,  455,  454,  454,  454,
      454,  454,  454,  454,  452,  452,  452,  456,  452,  452,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  457,
      457,   51,   51,   51,   51,   51,   51,  456,  458,  458,
      458,  458,  458,  458,  458,  458,  458,  458,  459,  459,
       70,   70,   70,   70,   70,   70,  458,  460,  460,  452,
      460,  461,  460,  460,  452,  460,  460,  460,  460,  460,
      460,  462,  463,  462,   94,   94,   94,   94,   94,   94,

      460,  460,  460,  452,  452,  453,  452,  452,  452,  452,
      452,  464,  452,  452,  452,  452,  452,  452,  454,  455,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  452,  456,  452,  456,  456,  456,  456,  456,
      465,  456,  456,  456,  456,  456,  456,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
      456,  458,  458,  458,  458,  458,  458,  466,  458,  458,
      458,  458,  458,  458,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,  458,  460,  460,
      460,  461,  460,  460,  452,  460,  467,  460,  460,  460,

      460,  460,  460,   94,  463,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,  460,  452,  452,
      464,  452,  452,  452,  452,  452,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  456,  456,
      465,  452,  456,  456,  456,  456,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,  458,  458,
      466,  458,  458,  458,  458,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,  460,  467,  460,
      460,  460,  460,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,  452,  452,  452,  452,  452,

      452,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      456,  456,  456,  456,  456,  456,   51,   51,   51,   51,
       51,   51,   51,   51,   51,  458,  458,  458,  458,  458,
      458,   70,   70,   70,   70,   70,   70,   70,   70,   70,
      460,  460,  460,  460,  460,   94,   94,   94,   94,   94,
       94,   94,   94,   94,  452,  452,  452,  454,  454,  454,
      454,  454,  454,  454,  454,  456,  456,  456,   51,   51,
       51,   51,   51,   51,   51,   51,  458,  458,  458,   70,
       70,   70,   70,   70,   70,   70,   70,  460,  460,   94,
       94,   94,   94,   94,   94,   94,   94,  452,  454,  454,

      454,  454,  454,  456,   51,   51,   51,   51,   51,  458,
       70,   70,   70,   70,   70,   94,   94,   94,   94,   94,
      452,  454,  454,  454,  456,   51,   51,   51,  458,   70,
       70,   70,   94,   94,   94,  452,  454,  456,   51,  458,
       70,   94,  452,  456,  458,  452,  456,  458,  452,  456,
      458,    0,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  452
    } ;

static yyconst flex_int16_t yy_nxt[1060] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   12,   19,   12,
       12,   20,   21,   22,   12,   23,   24,   25,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   27,   26,
       28,   26,   26,   29,   30,   26,   31,   26,   26,   26,
       26,   32,   33,   26,   26,   34,   26,   35,   36,   37,
       38,   39,   40,   41,   16,   17,   42,   38,   43,   38,
       38,   44,   45,   46,   12,   47,   48,   49,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   27,   50,
       51,   50,   50,   52,   53,   50,   54,   50,   50,   50,
       50,   55,   56,   50,   50,   57,   50,   35,   58,   37,

       59,   39,   40,   60,   16,   17,   61,   12,   62,   59,
       59,   63,   64,   65,   59,   66,   67,   68,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   27,   69,
       70,   69,   69,   71,   72,   69,   73,   69,   69,   69,
       69,   74,   75,   69,   69,   76,   69,   35,   77,   37,
       78,   79,   80,   81,   82,   83,   84,   78,   85,   78,
       78,   86,   87,   88,   78,   89,   90,   91,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   93,   92,
       94,   92,   92,   95,   96,   92,   97,   92,   92,   92,
       92,   98,   99,   92,   92,  100,   92,  101,  102,  103,

      111,  113,  128,  114,  112,  122,  123,  129,  125,  119,
      126,  115,  140,  124,  127,  142,  141,  143,  150,  151,
      158,  148,  148,  115,  159,  144,  152,  153,  148,  154,
      148,  185,  167,  155,  195,  156,  168,  144,  134,  175,
      157,  134,  148,  109,  134,  134,  134,  134,  134,  134,
      134,  160,  234,  134,  134,  134,  169,  148,  170,  177,
      178,  175,  175,  186,  235,  215,  171,  179,  180,  187,
      181,  175,  183,  204,  182,  175,  189,  184,  171,  175,
      106,  111,  217,  451,  213,  197,  134,  134,  204,  214,
      134,  204,  247,  134,  134,  134,  134,  134,  134,  134,

      148,  450,  134,  134,  134,  198,  110,  199,  207,  208,
      204,  204,  216,  223,  220,  200,  209,  210,  189,  211,
      204,  224,  106,  212,  148,  248,  220,  200,  149,  139,
      225,  225,  249,  224,  226,  134,  162,  240,  148,  162,
      250,  148,  162,  449,  162,  162,  162,  162,  162,  240,
      162,  162,  162,  162,  113,  243,  114,  142,  253,  143,
      148,  245,  245,  244,  115,  246,  166,  144,  251,  148,
      254,  148,  258,  256,  260,  244,  115,  148,  268,  144,
      148,  266,  255,  286,  162,  162,  260,  175,  162,  175,
      262,  162,  204,  162,  162,  162,  162,  162,  263,  162,

      162,  162,  162,  169,  175,  170,  269,  264,  264,  273,
      263,  265,  448,  171,  175,  267,  270,  175,  272,  175,
      175,  274,  175,  277,  275,  171,  176,  204,  175,  287,
      222,  204,  285,  162,  189,  189,  221,  189,  189,  189,
      189,  189,  447,  189,  189,  189,  189,  196,  189,  189,
      189,  189,  280,  452,  198,  278,  199,  282,  282,  221,
      281,  283,  189,  284,  200,  288,  204,  278,  290,  295,
      204,  204,  281,  204,  204,  293,  200,  323,  318,  446,
      148,  189,  189,  189,  189,  189,  148,  189,  189,  189,
      189,  189,  291,  189,  189,  189,  189,  322,  189,  189,

      189,  189,  204,  223,  292,  297,  297,  148,  204,  298,
      243,  299,  189,  300,  300,  312,  312,  301,  314,  313,
      315,  315,  369,  299,  316,  206,  148,  317,  319,  320,
      314,  189,  189,  189,  221,  242,  148,  221,  221,  148,
      321,  148,  148,  325,  262,  324,  148,  221,  148,  327,
      327,  332,  329,  328,  330,  330,  335,  333,  331,  334,
      175,  221,  336,  175,  329,  175,  337,  175,  175,  338,
      175,  175,  175,  280,  339,  340,  175,  148,  175,  371,
      221,  343,  221,  221,  242,  346,  221,  221,  445,  221,
      341,  341,  347,  343,  342,  344,  344,  204,  348,  345,

      204,  349,  351,  350,  352,  204,  204,  204,  353,  148,
      221,  204,  204,  204,  354,  356,  356,  204,  372,  357,
      367,  367,  380,  148,  368,  373,  175,  427,  148,  221,
      148,  221,  221,  452,  148,  221,  221,  374,  376,  378,
      378,  383,  175,  379,  382,  221,  148,  175,  175,  384,
      387,  385,  204,  175,  392,  393,  388,  388,  175,  221,
      389,  390,  204,  204,  394,  204,  395,  204,  397,  405,
      407,  148,  409,  406,  148,  148,  204,  408,  221,  412,
      221,  221,  452,  148,  221,  221,  148,  221,  411,  175,
      175,  413,  414,  415,  417,  175,  175,  416,  418,  204,

      419,  175,  428,  204,  204,  420,  426,  204,  221,  204,
      148,  430,  148,  431,  175,  432,  433,  175,  434,  204,
      435,  444,  204,  175,  439,  443,  148,  221,  204,  221,
      441,  442,  175,  204,  106,  106,  204,  204,  106,  106,
      106,  106,  120,  120,  175,  120,  120,  120,  120,  120,
      134,  175,  440,  148,  134,  134,  134,  148,  148,  438,
      437,  148,  148,  148,  162,  436,  204,  204,  175,  162,
      162,  162,  175,  175,  429,  148,  148,  175,  175,  175,
      189,  189,  425,  189,  189,  424,  189,  189,  192,  192,
      423,  192,  192,  192,  192,  192,  204,  204,  422,  204,

      204,  421,  204,  204,  205,  205,  204,  205,  205,  205,
      205,  205,  221,  221,  221,  221,  221,  221,  221,  221,
      241,  241,  241,  241,  241,  241,  241,  241,  261,  261,
      261,  261,  261,  261,  261,  261,  279,  279,  279,  279,
      279,  279,  279,  279,  204,  204,  389,  389,  175,  175,
      175,  379,  379,  410,  148,  148,  148,  368,  368,  404,
      403,  402,  401,  400,  399,  357,  357,  398,  396,  391,
      204,  345,  345,  342,  342,  386,  381,  175,  331,  331,
      328,  328,  377,  375,  370,  148,  316,  316,  313,  313,
      366,  365,  364,  363,  362,  361,  360,  359,  358,  301,

      301,  298,  298,  355,  204,  204,  204,  283,  283,  175,
      175,  175,  265,  265,  326,  148,  148,  148,  246,  246,
      311,  310,  309,  308,  307,  306,  305,  304,  303,  302,
      226,  226,  452,  296,  294,  204,  289,  120,  204,  193,
      190,  276,  175,  271,  175,  259,  257,  148,  252,  148,
      239,  135,  238,  237,  236,  233,  232,  231,  230,  229,
      228,  227,  222,  219,  107,  104,  218,  120,  203,  202,
      201,  196,  194,  193,  191,  190,  188,  174,  173,  172,
      166,  165,  164,  163,  161,  147,  146,  145,  139,  138,
      137,  136,  135,  133,  132,  131,  130,  121,  118,  117,

      116,  110,  109,  108,  107,  105,  104,  452,   11,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  452
    } ;

static yyconst flex_int16_t yy_chk[1060] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,

       21,   22,   31,   22,   21,   29,   29,   31,   30,  454,
       30,   22,   45,   29,   30,   46,   45,   46,   52,   52,
       55,   52,   56,   22,   56,   46,   52,   53,   55,   53,
       53,   74,   64,   53,   85,   54,   64,   46,   50,   74,
       54,   50,   54,   85,   50,   50,   50,   50,   50,   50,
       50,   57,  129,   50,   50,   50,   65,   57,   65,   71,
       71,   75,   71,   75,  129,   98,   65,   71,   72,   76,
       72,   72,   73,   98,   72,   76,   82,   73,   65,   73,
       82,   87,  100,  448,   97,   87,   50,   51,  100,   97,
       51,   97,  149,   51,   51,   51,   51,   51,   51,   51,

      149,  447,   51,   51,   51,   88,  110,   88,   95,   95,
       99,   95,   99,  113,  110,   88,   95,   96,  192,   96,
       96,  113,  192,   96,  150,  150,  110,   88,   51,  139,
      115,  115,  151,  113,  115,   51,   69,  139,  152,   69,
      152,  151,   69,  446,   69,   69,   69,   69,   69,  139,
       69,   69,   69,   69,  114,  142,  114,  143,  155,  143,
      155,  144,  144,  142,  114,  144,  166,  143,  153,  153,
      157,  158,  160,  158,  166,  142,  114,  160,  178,  143,
      157,  176,  157,  208,   69,   70,  166,  178,   70,  176,
      169,   70,  208,   70,   70,   70,   70,   70,  169,   70,

       70,   70,   70,  170,  179,  170,  179,  171,  171,  184,
      169,  171,  445,  170,  177,  177,  180,  180,  182,  184,
      182,  184,  185,  187,  185,  170,   70,  209,  187,  209,
      197,  207,  207,   70,   92,   92,  197,   92,   92,   92,
       92,   92,  444,   92,   92,   92,   92,  196,   92,   92,
       92,   92,  198,  279,  199,  196,  199,  200,  200,  279,
      198,  200,   92,  206,  199,  210,  210,  196,  212,  217,
      212,  206,  198,  215,  217,  215,  199,  254,  248,  443,
      254,   92,   92,   92,   94,   94,  248,   94,   94,   94,
       94,   94,  214,   94,   94,   94,   94,  253,   94,   94,

       94,   94,  214,  223,  214,  220,  220,  253,  442,  220,
      243,  223,   94,  224,  224,  240,  240,  224,  243,  240,
      244,  244,  317,  223,  244,   94,  317,  247,  250,  251,
      243,   94,   94,   94,  141,  141,  250,  141,  141,  247,
      252,  251,  256,  258,  262,  256,  258,  141,  252,  260,
      260,  266,  262,  260,  263,  263,  270,  267,  263,  269,
      441,  141,  271,  266,  262,  267,  272,  269,  270,  273,
      271,  275,  273,  280,  275,  277,  272,  320,  277,  320,
      141,  280,  141,  168,  168,  284,  168,  168,  440,  168,
      278,  278,  285,  280,  278,  281,  281,  284,  287,  281,

      285,  288,  290,  289,  291,  293,  287,  291,  293,  439,
      168,  289,  290,  288,  295,  299,  299,  295,  321,  299,
      314,  314,  332,  322,  314,  322,  332,  407,  407,  168,
      321,  168,  241,  241,  323,  241,  241,  323,  325,  329,
      329,  336,  335,  329,  335,  241,  325,  337,  338,  337,
      340,  338,  349,  336,  349,  350,  343,  343,  340,  241,
      343,  346,  351,  352,  351,  346,  352,  350,  354,  370,
      373,  370,  375,  372,  375,  373,  354,  374,  241,  383,
      241,  261,  261,  372,  261,  261,  374,  261,  381,  383,
      381,  384,  385,  386,  393,  386,  384,  391,  394,  391,

      395,  385,  408,  394,  393,  396,  406,  396,  261,  395,
      408,  412,  406,  413,  413,  414,  417,  412,  418,  418,
      419,  438,  417,  414,  427,  436,  427,  261,  419,  261,
      431,  434,  431,  434,  453,  453,  435,  433,  453,  453,
      453,  453,  455,  455,  432,  455,  455,  455,  455,  455,
      456,  430,  429,  428,  456,  456,  456,  457,  426,  425,
      423,  457,  457,  457,  458,  421,  420,  416,  415,  458,
      458,  458,  459,  411,  410,  409,  405,  459,  459,  459,
      460,  460,  404,  460,  460,  402,  460,  460,  461,  461,
      401,  461,  461,  461,  461,  461,  462,  462,  400,  462,

      462,  398,  462,  462,  463,  463,  397,  463,  463,  463,
      463,  463,  464,  464,  464,  464,  464,  464,  464,  464,
      465,  465,  465,  465,  465,  465,  465,  465,  466,  466,
      466,  466,  466,  466,  466,  466,  467,  467,  467,  467,
      467,  467,  467,  467,  392,  390,  389,  388,  387,  382,
      380,  379,  378,  377,  376,  371,  369,  368,  367,  366,
      364,  363,  362,  361,  359,  357,  356,  355,  353,  348,
      347,  345,  344,  342,  341,  339,  334,  333,  331,  330,
      328,  327,  326,  324,  319,  318,  316,  315,  313,  312,
      311,  310,  309,  308,  307,  306,  305,  304,  302,  301,

      300,  298,  297,  296,  294,  292,  286,  283,  282,  276,
      274,  268,  265,  264,  259,  257,  255,  249,  246,  245,
      239,  238,  236,  234,  233,  232,  231,  230,  228,  227,
      226,  225,  221,  219,  216,  213,  211,  205,  204,  193,
      190,  186,  183,  181,  175,  165,  159,  156,  154,  148,
      138,  135,  132,  131,  130,  127,  126,  125,  124,  123,
      122,  121,  112,  109,  107,  104,  102,   93,   91,   90,
       89,   86,   84,   83,   81,   79,   77,   68,   67,   66,
       63,   62,   61,   60,   58,   49,   48,   47,   44,   43,
       42,   41,   39,   36,   34,   33,   32,   28,   25,   24,

       23,   20,   19,   18,   17,   15,   13,   11,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  452,  452,  452,  452
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[50] =
    {   0,
0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
++(yy_lp); \
goto find_rule; \
}

static int yy_more_offset = 0;
static int yy_prev_more_offset = 0;
#define yymore() ((yy_more_offset) = yy_flex_strlen( yytext ))
#define YY_NEED_STRLEN
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET \
	{ \
	(yy_more_offset) = (yy_prev_more_offset); \
	yyleng -= (yy_more_offset); \
	}
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "script.l"
#line 6 "script.l"
static char lexrcsid[] = "$Id: script.l,v 1.3 2005/07/01 10:03:01 svitak Exp $";

/*
** $Log: script.l,v $
** Revision 1.3  2005/07/01 10:03:01  svitak
** Misc fixes to address compiler warnings, esp. providing explicit types
** for all functions and cleaning up unused variables.
**
** Revision 1.2  2005/06/27 19:00:34  svitak
** Added explicit types to untyped functions and fixed return values as
** appropriate. Initialized values explicitly when it was unclear if
** they were being used uninitialized (may not apply to all files being
** checked in in this batch).
**
** Revision 1.1.1.1  2005/06/14 04:38:28  svitak
** Import from snapshot of CalTech CVS tree of June 8, 2005
**
** Revision 1.7  2001/04/18 22:39:36  mhucka
** Miscellaneous portability fixes, mainly for SGI IRIX.
**
** Revision 1.6  1999/10/17 04:53:03  mhucka
** Added forward declarations for Pushyybgin(), Popyybgin().
**
** Revision 1.5  1999/08/22 04:42:13  mhucka
** Various fixes, mostly for Red Hat Linux 6.0
**
** Revision 1.4  1995/05/01 18:25:08  dhb
** changes ifdef irix to ifdef sgi
**
 * Revision 1.3  1995/04/29  01:19:50  dhb
 * Replaced lexer implementation specific code and made lexer
 * work with flex and bison.
 *
 * Revision 1.2  1995/04/14  01:03:20  dhb
 * Null change to force patch and reprocessing by lex.
 *
 * Revision 1.1  1995/01/13  01:09:48  dhb
 * Initial revision
 *
**
** This file is from GENESIS 1.4.1
**
 * Revision 1.1  1992/12/11  21:18:51  dhb
 * Initial revision
 *
*/

#include "output.h"

#ifdef sgi
extern void exit();
#endif

#ifdef FLEX_SCANNER

static int GEN_moreinput();

#define YY_INPUT(buf,result,n)	result = GEN_moreinput(buf, n)

#else

#undef input
#define input() (((yytchar=yysptr>yysbuf?U(*--yysptr):nextchar(0))==10?(yylineno++,yytchar):yytchar)==EOF?0:yytchar)

    /* YY_START - return current BEGIN state as value usable with BEGIN */
#define	YY_START	(yybgin-yysvec - 1)
#define	YY_NULL		0

#endif

/* Forward declarations */
static void Ccomment();
static void Pushyybgin();
static void Popyybgin();

#ifdef LEXTEST
#    define	lextoken(tok)	printf("%s ==> %s\n", yytext, "tok")
#    define	lexchar(ch)	printf("'%c'\n", ch)
#else
#  ifdef YACCTEST
#    define	lextoken(tok)	{ printf("%s ==> %s\n", yytext, "tok"); return(tok); }
#    define	lexchar(ch)	{ printf("'%c'\n", ch); return(ch); }
#  else
#    define	lextoken(tok)	{inCommand = 1; return(tok);}
#    define	lexchar(ch)	{(ch == '\n' && !continuation) ? inCommand = 0: 0; return(ch); }
#  endif
#endif

#define	BGINSTKSIZE	100

static int	yybginstk[BGINSTKSIZE];
static int	yybginidx = 0;
static int	continuation = 0;
static int	inCommand = 0;
int		Indentation = 0;

/* Forward declarations */
static void Pushyybgin();
static void Popyybgin();

#line 113 "script.l"
/* I use this area to hold things that I might want back */

#ifdef COMMENT
<CPPCOMMENT>[^\n]*	Popyybgin();
"//"			Pushyybgin(CPPCOMMENT);

\\\n			continuation = 0;
#endif
#line 1098 "lex.yy.c"

#define INITIAL 0
#define LIT 1
#define FUNCLIT 2
#define CCOMMENT 3
#define CPPCOMMENT 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 123 "script.l"


#line 1292 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 453 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1009 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
					{
					(yy_full_match) = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = (yy_prev_more_offset); yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 125 "script.l"
Output(yytext, NULL);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 126 "script.l"
Output("*", NULL);
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 127 "script.l"
Output("\n", NULL);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 128 "script.l"
{
			  if (inCommand)
			    Output("*/", "\n", NULL);
			  else
			    Output("*/", NULL);
			  Popyybgin();
			};
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 135 "script.l"
{
			  OutputIndentation();
			  Output("/*", NULL);
			  Pushyybgin(CCOMMENT);
			};
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 141 "script.l"
{
			  OutputIndentation();
			  if (inCommand)
			    Output(yytext, "\n", NULL);
			  else
			    Output(yytext, NULL);
			};
	YY_BREAK
case 7:
/* rule 7 can match eol */
#line 150 "script.l"
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 150 "script.l"
{
			  if (!continuation)
			    {
			      Indentation = 0;
			      lexchar('\n');
			    }
			  else
			    {
			      continuation = 0;
			      lexchar(WHITESPACE);
			    }
			}
	YY_BREAK
case 9:
/* rule 9 can match eol */
#line 164 "script.l"
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 164 "script.l"
{
			  if (!continuation)
			    {
			      Indentation = 0;
			      lexchar('\n');
			    }

			  continuation = 0;
			}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 174 "script.l"
{
			  /* extern char*	strchr(); */
			  char*		comment;

			  comment = strchr(yytext, '/');
			  if (comment != NULL && comment[1] == '/')
			    {
			      OutputIndentation();
			      Output(comment, "\n", NULL);
			    }

			  continuation = 1;
			}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 188 "script.l"
{
			  char	ch;

			  ch = input();
			  if (ch == '\n')
			    {
			      fprintf(stderr, 
				  "Missing closing quote in string constant\n");
			      fprintf(stderr, "conversion failed\n");
			      exit(1);
			      /* No Return */
			    }

			  if (yytext[yyleng-1] == '\\')
			    {
			      yytext[yyleng-1] = '"';
			      yyless(yyleng-1);
			      yymore();
			    }
			  else
			    {
			      yylval.str = (char *) strsave(yytext+1);
			      lextoken(STRCONST);
			    }
			};
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 214 "script.l"
{
			  yylval.str = (char *) strsave(yytext);
			  lextoken(DOLLARARG);
			}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 219 "script.l"
{ 
			  yylval.str = (char *) strsave(yytext);
			  lextoken(LITERAL);
			};
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 224 "script.l"
{ 
			  yylval.str = (char *) strsave(yytext);
			  lextoken(LITERAL);
			};
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 229 "script.l"
lextoken(WHITESPACE);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 230 "script.l"
{
			  if (Indentation == 0)
			    {
			      char*	cp;

			      SetOutputIndentation(yytext);
			      Indentation = 1;
			      /*
			      cp = yytext;
			      for (cp = yytext; *cp != '\0'; cp++)
				if (*cp == '\t')
				    Indentation += 8 - Indentation%8;
				else
				    Indentation++;
			      */
			    }
			};
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 248 "script.l"
{
		  if (!Indentation)
		      SetOutputIndentation("");
		  Indentation = 1;
		  lextoken(INCLUDE);
		};
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 255 "script.l"
lextoken(ENDSCRIPT);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 257 "script.l"
{
		  if (!Indentation)
		      SetOutputIndentation("");
		  Indentation = 1;
		  lextoken(BREAK);
		};
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 264 "script.l"
{
		  if (!Indentation)
		      SetOutputIndentation("");
		  Indentation = 1;
		  lextoken(RETURN);
		};
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 271 "script.l"
{
		  if (!Indentation)
		      SetOutputIndentation("");
		  Indentation = 1;
		  lextoken(WHILE);
		};
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 278 "script.l"
{
		  if (!Indentation)
		      SetOutputIndentation("");
		  Indentation = 1;
		  lextoken(IF);
		};
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 285 "script.l"
{
		  if (!Indentation)
		      SetOutputIndentation("");
		  Indentation = 1;
		  lextoken(ELSE);
		};
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 292 "script.l"
{
		  if (!Indentation)
		      SetOutputIndentation("");
		  Indentation = 1;
		  lextoken(FOR);
		};
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 299 "script.l"
{
		  if (!Indentation)
		      SetOutputIndentation("");
		  Indentation = 1;
		  lextoken(FOREACH);
		};
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 306 "script.l"
{
		  if (!Indentation)
		      SetOutputIndentation("");
		  Indentation = 1;
		  lextoken(END);
		};
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 313 "script.l"
{
		  if (!Indentation)
		      SetOutputIndentation("");
		  Indentation = 1;
		  lextoken(FUNCTION);
		};
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 320 "script.l"
{
		  if (!Indentation)
		      SetOutputIndentation("");
		  Indentation = 1;
		  lextoken(EXTERN);
		};
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 327 "script.l"
{
		  if (!Indentation)
		      SetOutputIndentation("");
		  Indentation = 1;
		  lextoken(INT);
		};
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 334 "script.l"
{
		  if (!Indentation)
		      SetOutputIndentation("");
		  Indentation = 1;
		  lextoken(FLOAT);
		};
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 341 "script.l"
{
		  if (!Indentation)
		      SetOutputIndentation("");
		  Indentation = 1;
		  lextoken(STR);
		};
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 348 "script.l"
lextoken(LT);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 349 "script.l"
lextoken(LE);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 350 "script.l"
lextoken(GT);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 351 "script.l"
lextoken(GE);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 352 "script.l"
lextoken(EQ);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 353 "script.l"
lextoken(NE);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 355 "script.l"
lextoken(OR);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 356 "script.l"
lextoken(AND);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 358 "script.l"
{
			  Result	*rp;

			  if (!Indentation)
			      SetOutputIndentation("");
			  Indentation = 1;

			  yylval.str = (char *) strsave(yytext);
			  if (!ReturnIdents &&
			      ((rp=SymtabLook(LocalSymbols, yytext)) != NULL ||
			       (rp=SymtabLook(&GlobalSymbols, yytext)) != NULL))
			    {
			      if (rp->r_type == FUNCTION)
				  { lextoken(FUNCREF); }
			      else
				  lextoken(VARREF);
			    }
			  else
			      lextoken(IDENT);
			};
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 379 "script.l"
{
			  yylval.str = (char *) strsave(yytext);
			  lextoken(INTCONST);
			}
	YY_BREAK
case 43:
#line 385 "script.l"
case 44:
#line 386 "script.l"
case 45:
YY_RULE_SETUP
#line 386 "script.l"
{
			  yylval.str = (char *) strsave(yytext);
			  lextoken(FLOATCONST);
			}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 391 "script.l"
{ Pushyybgin(0); lexchar('{'); };
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 392 "script.l"
{ Popyybgin(); lexchar('}'); };
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 394 "script.l"
{
			  if (yytext[0] == '\n')
			    Indentation = 0;
			  lexchar(yytext[0])
			};
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 399 "script.l"
ECHO;
	YY_BREAK
#line 1827 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(LIT):
			case YY_STATE_EOF(FUNCLIT):
			case YY_STATE_EOF(CCOMMENT):
			case YY_STATE_EOF(CPPCOMMENT):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 453 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 453 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 452);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 399 "script.l"



/*
** Lexer routines to push and pop the lexer begin state
*/

static void Pushyybgin(start)

int	start;

{	/* Pushyybgin --- Push to another lexer begin state */

	if (yybginidx == BGINSTKSIZE)
	    yyerror("Pushyybgin: lexer begin state stack overflow");
	    /* No Return */

	yybginstk[yybginidx++] = YY_START;
	BEGIN start;

}	/* Pushyybgin */



static void Popyybgin()

{	/* Popyybgin --- Pop to previous lexer begin state */

	if (yybginidx == 0)
	    yyerror("Popyybgin: lexer begin state stack underflow");
	    /* No Return */

	BEGIN yybginstk[--yybginidx];

}	/* Popyybgin */



static FILE*	CurFs = NULL;

void InputFs(fs)

FILE*	fs;

{
	CurFs = fs;
}


/*
** Local routine to get input characters
**
** For FLEX_SCANNER we don't need to do this buffering since
** flex does it for us.  We still provide nextchar() as a method
** for flushing the lexer input.  The *END SCRIPT* stuff will be
** handled in the YY_INPUT macro.
*/

static int GEN_moreinput(buf, n)

char*	buf;
int	n;

{
	char*	cp;
	int	result;

        if (CurFs == NULL)
            CurFs = stdin;

	do
	  {
	    cp = (char *) fgets(buf, n, CurFs);
	  }
       while (cp != NULL && *cp == '\0');

	if (cp == NULL)
	  {
	    result = YY_NULL; /* END OF INPUT */
	  }
	else
	    result = strlen(buf);

	return result;

}

#ifdef FLEX_SCANNER

int nextchar(flush)

int	flush;

{
	if (flush)
	  {
	    yybginidx = 0;
	    BEGIN 0;
	    yyrestart(yyin); /* flushes flex input buffer */
	  }

	return 0;
}

#else
int nextchar(flush)

{	/* nextchar --- Return next char to lexer */

	static char	buf[100] = "";
	static char	*cp = buf;

        if (CurFs == NULL)
            CurFs = stdin;

	if (flush)
	  {
	    yybginidx = 0;
	    BEGIN 0;
	    yysptr = yysbuf;
	    cp = buf;
	    *cp = '\0';
	    return;
	  }

	while (cp != NULL && *cp == '\0')
	    cp = (char *) fgets(buf, sizeof(buf), CurFs);

	if (cp == NULL)
	  {
	    /*
	    sprintf(buf, "*ENDSCRIPT*\n");
	    cp = buf;
	    */
	    return EOF;
	  }

	return(*cp++);

}	/* nextchar */
#endif

/*
** For systems that don't have a lex library, we define some of the support
** routines.
*/

/* mds3 changes */
#ifdef i860
yyless(x)
{
extern char yytext[];
register char *lastch, *ptr;
extern int yyleng;
extern int yyprevious;
lastch = yytext+yyleng;
if (x>=0 && x <= yyleng)
        ptr = x + yytext;
else
        ptr = x;
while (lastch > ptr)
        yyunput(*--lastch);
*lastch = 0;
if (ptr >yytext)
        yyprevious = *--lastch;
yyleng = ptr-yytext;
}

yywrap()
{
return 1;
}
#endif
/* end of mds3 changes */

