#define PF(F,T) HashFunc("F",F,"T")
void FUNC_basic(){
extern int do_simulate();
extern int do_ps();
extern int do_date();
extern int do_reset();
extern int do_debug();
extern int do_srandom();
extern int do_silent();
extern int do_notes();
extern int do_pwe();
extern int do_pushe();
extern int do_pope();
extern int do_show_estack();
extern int do_set();
extern int do_show();
extern int do_create();
extern int do_copy();
extern int do_move();
extern int do_create_map();
extern int do_position();
extern int do_delete_element();
extern int do_getinfo();
extern int CheckSimulation();
extern int do_list_elements();
extern int do_change_element();
extern int do_help();
extern int do_show_binding();
extern int ShowClocks();
extern int do_set_clock();
extern int SetBreakFlag();
extern int do_clean();
extern int do_add_msg();
extern int do_show_msg();
extern int do_add_object();
extern int do_list_objects();
extern int do_show_object();
extern int ExecuteTasks();
extern int do_list_classes();
extern int do_add_class();
extern int do_clear_schedule();
extern int do_add_schedule();
extern int Reschedule();
extern int do_list_tasks();
extern int do_add_action();
extern int do_call_element();
extern int ResetErrors();
extern int do_logon();
extern int do_logoff();
extern int StepSimulation();
extern int TStepSimulation();
extern int do_alias();
extern int do_enable();
extern int do_disable();
extern int do_element_clock();
extern int do_delete_msg();
extern float do_getclock();
extern char* do_getfield();
extern char** do_construct_list();
extern char** do_readfile();
extern int do_writefile();
extern int do_flushfile();
extern int do_closefile();
extern int do_openfile();
extern int do_showfiles();
extern int BufferCopy();
extern int BufferCreate();
extern int do_exists();
extern int do_setobjenv();
extern char* do_getobjenv();
extern int do_setdefault();
extern char* do_getdefault();
extern char* do_getmsg();
extern float do_getstatus();
extern int do_showstatus();
extern int do_insert_event();
extern char** do_getfields();
extern char* do_pathname();
extern int do_checkeof();
extern int do_saveparms();
extern int do_restoreparms();
extern int Simulate();
extern int BUILD_Simulate();
extern int do_set_method();
extern float do_version();
extern int do_addfield();
extern int do_deletefield();
extern int do_setdefault();
extern char* do_getdefault();
extern int do_add_extobject();
extern int do_add_msglist();
extern int do_delete_msglist();
extern int do_delete_class();
extern int do_add_class();
extern int do_delete_action();
extern int do_setfieldprot();
HashFunc("do_simulate",do_simulate,"int");
HashFunc("do_ps",do_ps,"int");
HashFunc("do_date",do_date,"int");
HashFunc("do_reset",do_reset,"int");
HashFunc("do_debug",do_debug,"int");
HashFunc("do_srandom",do_srandom,"int");
HashFunc("do_silent",do_silent,"int");
HashFunc("do_notes",do_notes,"int");
HashFunc("do_pwe",do_pwe,"int");
HashFunc("do_pushe",do_pushe,"int");
HashFunc("do_pope",do_pope,"int");
HashFunc("do_show_estack",do_show_estack,"int");
HashFunc("do_set",do_set,"int");
HashFunc("do_show",do_show,"int");
HashFunc("do_create",do_create,"int");
HashFunc("do_copy",do_copy,"int");
HashFunc("do_move",do_move,"int");
HashFunc("do_create_map",do_create_map,"int");
HashFunc("do_position",do_position,"int");
HashFunc("do_delete_element",do_delete_element,"int");
HashFunc("do_getinfo",do_getinfo,"int");
HashFunc("CheckSimulation",CheckSimulation,"int");
HashFunc("do_list_elements",do_list_elements,"int");
HashFunc("do_change_element",do_change_element,"int");
HashFunc("do_help",do_help,"int");
HashFunc("do_show_binding",do_show_binding,"int");
HashFunc("ShowClocks",ShowClocks,"int");
HashFunc("do_set_clock",do_set_clock,"int");
HashFunc("SetBreakFlag",SetBreakFlag,"int");
HashFunc("do_clean",do_clean,"int");
HashFunc("do_add_msg",do_add_msg,"int");
HashFunc("do_show_msg",do_show_msg,"int");
HashFunc("do_add_object",do_add_object,"int");
HashFunc("do_list_objects",do_list_objects,"int");
HashFunc("do_show_object",do_show_object,"int");
HashFunc("ExecuteTasks",ExecuteTasks,"int");
HashFunc("do_list_classes",do_list_classes,"int");
HashFunc("do_add_class",do_add_class,"int");
HashFunc("do_clear_schedule",do_clear_schedule,"int");
HashFunc("do_add_schedule",do_add_schedule,"int");
HashFunc("Reschedule",Reschedule,"int");
HashFunc("do_list_tasks",do_list_tasks,"int");
HashFunc("do_add_action",do_add_action,"int");
HashFunc("do_call_element",do_call_element,"int");
HashFunc("ResetErrors",ResetErrors,"int");
HashFunc("do_logon",do_logon,"int");
HashFunc("do_logoff",do_logoff,"int");
HashFunc("StepSimulation",StepSimulation,"int");
HashFunc("TStepSimulation",TStepSimulation,"int");
HashFunc("do_alias",do_alias,"int");
HashFunc("do_enable",do_enable,"int");
HashFunc("do_disable",do_disable,"int");
HashFunc("do_element_clock",do_element_clock,"int");
HashFunc("do_delete_msg",do_delete_msg,"int");
HashFunc("do_getclock",do_getclock,"float");
HashFunc("do_getfield",do_getfield,"char*");
HashFunc("do_construct_list",do_construct_list,"char**");
HashFunc("do_readfile",do_readfile,"char**");
HashFunc("do_writefile",do_writefile,"int");
HashFunc("do_flushfile",do_flushfile,"int");
HashFunc("do_closefile",do_closefile,"int");
HashFunc("do_openfile",do_openfile,"int");
HashFunc("do_showfiles",do_showfiles,"int");
HashFunc("BufferCopy",BufferCopy,"int");
HashFunc("BufferCreate",BufferCreate,"int");
HashFunc("do_exists",do_exists,"int");
HashFunc("do_setobjenv",do_setobjenv,"int");
HashFunc("do_getobjenv",do_getobjenv,"char*");
HashFunc("do_setdefault",do_setdefault,"int");
HashFunc("do_getdefault",do_getdefault,"char*");
HashFunc("do_getmsg",do_getmsg,"char*");
HashFunc("do_getstatus",do_getstatus,"float");
HashFunc("do_showstatus",do_showstatus,"int");
HashFunc("do_insert_event",do_insert_event,"int");
HashFunc("do_getfields",do_getfields,"char**");
HashFunc("do_pathname",do_pathname,"char*");
HashFunc("do_checkeof",do_checkeof,"int");
HashFunc("do_saveparms",do_saveparms,"int");
HashFunc("do_restoreparms",do_restoreparms,"int");
HashFunc("Simulate",Simulate,"int");
HashFunc("BUILD_Simulate",BUILD_Simulate,"int");
HashFunc("do_set_method",do_set_method,"int");
HashFunc("do_version",do_version,"float");
HashFunc("do_addfield",do_addfield,"int");
HashFunc("do_deletefield",do_deletefield,"int");
HashFunc("do_setdefault",do_setdefault,"int");
HashFunc("do_getdefault",do_getdefault,"char*");
HashFunc("do_add_extobject",do_add_extobject,"int");
HashFunc("do_add_msglist",do_add_msglist,"int");
HashFunc("do_delete_msglist",do_delete_msglist,"int");
HashFunc("do_delete_class",do_delete_class,"int");
HashFunc("do_add_class",do_add_class,"int");
HashFunc("do_delete_action",do_delete_action,"int");
HashFunc("do_setfieldprot",do_setfieldprot,"int");
}
#undef PF
