#define concpool_CONCEN 0
#define concpool_STOREINFLUX 4
#define concpool_STOREOUTFLUX 5
#define concpool_BUFFER 10
#define concpool_HILLPUMP 14
#define difshell_INFLUX 0
#define difshell_OUTFLUX 1
#define difshell_FINFLUX 2
#define difshell_FOUTFLUX 3
#define difshell_STOREINFLUX 4
#define difshell_STOREOUTFLUX 5
#define difshell_DIFF_DOWN 6
#define difshell_DIFF_UP 7
#define difshell_BUFFER 10
#define difshell_TAUPUMP 11
#define difshell_EQTAUPUMP 12
#define difshell_MMPUMP 13
#define difshell_HILLPUMP 14
#define taupump_VOLTAGE 0
#define mmpump_CONCEN 0
#define mmpump_MMKD 1
#define hillpump_MMKD 1
#define fixbuffer_CONCEN 0
#define difbuffer_CONCEN 0
#define difbuffer_BDIFF_DOWN 1
#define difbuffer_DIFF_DOWN 1
#define difbuffer_BDIFF_UP 2
#define difbuffer_DIFF_UP 2
#define dif2buffer_CONCEN 0
#define dif2buffer_BDIFF_DOWN 1
#define dif2buffer_BDIFF_UP 2
#define fura2_CONCEN 0
