#define RESETBUFFER 1001
#define synchan_VOLTAGE 0
#define synchan_ACTIVATION 1
#define synchan_RAND_ACTIVATION 2
#define synchan_MOD 3
#define synchan_SPIKE -1
#define synchan2_VOLTAGE 0
#define synchan2_ACTIVATION 1
#define synchan2_RAND_ACTIVATION 2
#define synchan2_MOD 3
#define synchan2_SPIKE -1
#define hebbsynchan_VOLTAGE 0
#define hebbsynchan_ACTIVATION 1
#define hebbsynchan_RAND_ACTIVATION 2
#define hebbsynchan_MOD 3
#define hebbsynchan_WEIGHT_CHANGE_MOD 4
#define hebbsynchan_SPIKE -1
#define facsynchan_VOLTAGE 0
#define facsynchan_SPIKE -1
#define spikegen_INPUT 0
#define spikegen_THRESH 1
#define randomspike_RATE 0
#define randomspike_MINMAX 1
#define SynS_object_VOLTAGE 0
#define SynG_object_VOLTAGE 0
#define SynG_object_CAF 1
#define SynG_object_CAS 2
#define SynG_object_POSTVOLTAGE 3
#define SynE_object_VOLTAGE 0
#define SynE_object_POSTVOLTAGE 1
