#define TABCREATE 200
#define TABFILL 201
#define TABDELETE 202
#define TABSAVE 203
#define TABREAD 204
#define TAB2FIELDS 207
#define TABOP 208
#define receptor_ODOR 0
#define receptor_GAIN 1
#define receptor2_VOLTAGE 0
#define receptor2_ODOR 1
#define receptor2_MODULATION 2
#define tabgate_VOLTAGE 0
#define tabgate_SUM_ALPHA 2
#define tabgate_PRD_ALPHA 3
#define tabgate_SUM_BETA 4
#define tabgate_PRD_BETA 5
#define tabgate_EREST 6
#define table_INPUT 0
#define table_SUM 1
#define table_PRD 2
#define table_INPUT2 3
#define table2D_INPUT 0
#define table2D_SUM 1
#define table2D_PRD 2
#define table2D_X 3
#define table2D_Y 4
#define tabchannel_VOLTAGE 0
#define tabchannel_CONCEN 1
#define tabchannel_DOMAINCONC 3
#define tabchannel_EK 4
#define tabchannel_ADD_GBAR 5
#define tab2Dchannel_VOLTAGE 0
#define tab2Dchannel_CONCEN 1
#define tab2Dchannel_CONCEN1 1
#define tab2Dchannel_CONCEN2 2
#define tab2Dchannel_DOMAINCONC 3
#define tab2Dchannel_EK 4
#define tab2Dchannel_ADD_GBAR 5
#define tabcurrent_VOLTAGE 0
#define tabcurrent_CONCEN 1
#define tabcurrent_CONCEN1 1
#define tabcurrent_CONCEN2 2
#define tabcurrent_DOMAINCONC 3
#define tabcurrent_ADD_GBAR 5
#define ddsyn_VOLTAGE 0
#define ddsyn_ACTIVATION 1
#define ddsyn_V_PRESYN 2
#define ddsyn_RAND_ACTIVATION 3
