
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int yylineno;

int yylineno = 1;

extern char yytext[];

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng + (yy_more_offset) >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( &yytext[(yy_more_offset)], (yytext_ptr), yyleng + 1 ); \
	yyleng += (yy_more_offset); \
	(yy_prev_more_offset) = (yy_more_offset); \
	(yy_more_offset) = 0; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 52
#define YY_END_OF_BUFFER 53
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[685] =
    {   0,
       53,   51,   52,   18,   51,   52,    8,   52,    7,   51,
       52,   51,   52,   12,   13,   51,   52,   51,   52,   51,
       52,   51,   52,   51,   52,   51,   52,   45,   51,   52,
       35,   51,   52,   51,   52,   37,   51,   52,   44,   51,
       52,   11,   51,   52,   44,   51,   52,   44,   51,   52,
       44,   51,   52,   44,   51,   52,   44,   51,   52,   44,
       51,   52,   44,   51,   52,   49,   51,   52,   51,   52,
       50,   51,   52,   16,   51,   52,   17,   18,   51,   52,
        3,    8,   52,    4,    7,   51,   52,   16,   51,   52,
       16,   51,   52,   16,   51,   52,   16,   51,   52,   16,

       51,   52,   16,   45,   51,   52,   16,   35,   51,   52,
       16,   51,   52,   16,   37,   51,   52,   16,   44,   51,
       52,   16,   44,   51,   52,   16,   44,   51,   52,   16,
       44,   51,   52,   16,   44,   51,   52,   16,   44,   51,
       52,   16,   44,   51,   52,   16,   44,   51,   52,   16,
       51,   52,   15,   51,   52,   15,   51,   52,   15,   51,
       52,   15,   51,   52,   15,   51,   52,   15,   51,   52,
       15,   45,   51,   52,   15,   35,   51,   52,   15,   51,
       52,   15,   37,   51,   52,   15,   44,   51,   52,   15,
       44,   51,   52,   15,   44,   51,   52,   15,   44,   51,

       52,   15,   44,   51,   52,   15,   44,   51,   52,   15,
       44,   51,   52,   15,   44,   51,   52,   15,   51,   52,
       18,   40,   12,   13,   13,   12,   14,   42,   43,   48,
        1,    2,   47,   45,   36,   39,   38,   44,   11,   44,
       44,   44,   44,   44,   44,   44,   24,   44,   44,   44,
       44,   44,   41,   16,   17,   18,   16,   40,   16,   42,
       16,   43,   16,   16,   48,    1,   16,    2,   16,   16,
       47,   16,   45,   16,   16,   36,   16,   39,   16,   38,
       16,   44,   16,   44,   16,   44,   16,   44,   16,   44,
       16,   44,   16,   44,   16,   44,   16,   24,   44,   16,

       44,   16,   44,   16,   44,   16,   44,   16,   41,   15,
       15,   40,   15,   42,   15,   43,   15,   15,   48,    1,
       15,    2,   15,   15,   47,   15,   45,   15,   15,   36,
       15,   39,   15,   38,   15,   44,   15,   44,   15,   44,
       15,   44,   15,   44,   15,   44,   15,   44,   15,   44,
       15,   24,   44,   15,   44,   15,   44,   15,   44,   15,
       44,   15,   41,    2,   10,    2,    9,   47,   48,   46,
       44,   44,   44,   29,   44,   44,   44,   27,   44,   44,
       44,   32,   44,   44,   34,   44,   44,   16,   16,    2,
       16,    6,   10,    2,    5,    9,   16,   47,   48,   16,

       16,   16,   46,   16,   44,   16,   44,   16,   44,   16,
       29,   44,   16,   44,   16,   44,   16,   27,   44,   16,
       44,   16,   44,   16,   32,   44,   16,   44,   16,   34,
       44,   16,   44,   15,   15,    2,   15,   15,   47,   48,
       15,   15,   15,   46,   15,   44,   15,   44,   15,   44,
       15,   29,   44,   15,   44,   15,   44,   15,   27,   44,
       15,   44,   15,   44,   15,   32,   44,   15,   44,   15,
       34,   44,   15,   44,   48,   47,   44,   26,   44,   25,
       44,   44,   44,   44,   44,   44,   44,   44,   16,   16,
       16,   48,   16,   16,   16,   47,   16,   44,   16,   26,

       44,   16,   25,   44,   16,   44,   16,   44,   16,   44,
       16,   44,   16,   44,   16,   44,   16,   44,   15,   15,
       15,   48,   15,   15,   15,   47,   15,   44,   15,   26,
       44,   15,   25,   44,   15,   44,   15,   44,   15,   44,
       15,   44,   15,   44,   15,   44,   15,   44,   47,   48,
       21,   44,   44,   33,   44,   44,   44,   44,   44,   23,
       44,   16,   16,   16,   47,   48,   16,   21,   44,   16,
       44,   16,   33,   44,   16,   44,   16,   44,   16,   44,
       16,   44,   16,   23,   44,   15,   15,   15,   47,   48,
       15,   21,   44,   15,   44,   15,   33,   44,   15,   44,

       15,   44,   15,   44,   15,   44,   15,   23,   44,   31,
       44,   44,   44,   44,   22,   44,   16,   16,   31,   44,
       16,   44,   16,   44,   16,   44,   16,   22,   44,   15,
       15,   31,   44,   15,   44,   15,   44,   15,   44,   15,
       22,   44,   28,   44,   44,   19,   44,   16,   16,   28,
       44,   16,   44,   16,   19,   44,   15,   15,   28,   44,
       15,   44,   15,   19,   44,   30,   44,   16,   16,   30,
       44,   15,   15,   30,   44,   16,   15,   16,   15,   20,
       16,   20,   15,   20
    } ;

static yyconst flex_int16_t yy_accept[362] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    7,    9,   12,   14,   18,   20,   22,
       24,   26,   28,   31,   34,   36,   39,   42,   45,   48,
       51,   54,   57,   60,   63,   66,   69,   71,   74,   77,
       81,   84,   88,   91,   94,   97,  100,  103,  107,  111,
      114,  118,  122,  126,  130,  134,  138,  142,  146,  150,
      153,  156,  159,  162,  165,  168,  171,  175,  179,  182,
      186,  190,  194,  198,  202,  206,  210,  214,  218,  221,
      222,  223,  225,  226,  227,  228,  229,  230,  230,  231,
      232,  233,  234,  235,  235,  236,  237,  238,  239,  240,

      241,  242,  243,  244,  245,  246,  247,  249,  250,  251,
      252,  253,  254,  255,  257,  259,  261,  263,  264,  266,
      268,  270,  272,  274,  275,  277,  279,  281,  283,  285,
      287,  289,  291,  293,  295,  297,  300,  302,  304,  306,
      308,  310,  311,  313,  315,  317,  318,  320,  322,  324,
      326,  328,  329,  331,  333,  335,  337,  339,  341,  343,
      345,  347,  349,  351,  354,  356,  358,  360,  362,  364,
      364,  364,  365,  366,  368,  370,  370,  370,  371,  372,
      373,  374,  376,  377,  378,  380,  381,  382,  384,  385,
      387,  388,  389,  390,  392,  394,  397,  400,  401,  402,

      404,  406,  408,  410,  413,  415,  417,  420,  422,  424,
      427,  429,  432,  434,  435,  436,  438,  441,  442,  443,
      445,  447,  449,  451,  454,  456,  458,  461,  463,  465,
      468,  470,  473,  475,  475,  475,  476,  476,  476,  477,
      478,  480,  482,  483,  484,  485,  486,  487,  488,  489,
      490,  491,  493,  494,  495,  497,  499,  502,  505,  507,
      509,  511,  513,  515,  517,  519,  520,  521,  523,  524,
      525,  527,  529,  532,  535,  537,  539,  541,  543,  545,
      547,  549,  549,  549,  551,  553,  554,  556,  557,  558,
      559,  560,  562,  563,  564,  567,  570,  572,  575,  577,

      579,  581,  583,  586,  587,  588,  591,  594,  596,  599,
      601,  603,  605,  607,  610,  610,  612,  613,  614,  615,
      617,  618,  621,  623,  625,  627,  630,  631,  634,  636,
      638,  640,  643,  643,  645,  646,  648,  649,  652,  654,
      657,  658,  661,  663,  666,  666,  668,  669,  672,  673,
      676,  676,  677,  678,  678,  679,  680,  681,  683,  685,
      685
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    1,    8,    1,    9,
        9,   10,   11,    9,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,    1,   16,   17,
       18,   19,    1,    1,   20,   20,   21,   22,   23,   20,
       20,   20,   24,   20,   20,   20,   20,   25,   20,   26,
       20,   27,   28,   29,   20,   20,   20,   20,   20,   20,
        1,   30,    1,    1,   20,    1,   31,   32,   33,   34,

       35,   36,   20,   37,   38,   20,   39,   40,   20,   41,
       42,   20,   20,   43,   44,   45,   46,   20,   47,   48,
       20,   20,   49,   50,   51,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[52] =
    {   0,
        1,    2,    3,    4,    1,    5,    2,    1,    6,    1,
        1,    1,    1,    1,    7,    8,    1,    1,    1,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    2,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    2,    1,
        2
    } ;

static yyconst flex_int16_t yy_base[373] =
    {   0,
        0,    0,   51,    0,  102,    0,    0,    0,    0,    0,
      757,  758,  754,  758,  758,  737,  151,  739,  745,  146,
      737,  147,  145,  733,  732,  731,    0,    0,  705,  122,
      125,  123,  712,  701,  708,  758,  694,  758,    0,  741,
      758,  758,  724,  733,  156,  725,  162,  160,  721,  720,
      719,  195,  245,  141,  145,  156,  143,  172,  173,  686,
        0,  717,  726,  167,  718,  184,  205,  714,  713,  712,
      295,  345,  181,  190,  198,  158,  180,  194,  679,  726,
      758,  223,    0,    0,  712,  758,  758,  701,  237,  758,
      239,  246,  252,  236,  758,  758,  758,    0,    0,  690,

      200,  690,  678,  680,  678,  679,    0,  233,  674,  675,
      679,  758,    0,  714,    0,    0,    0,  690,  256,    0,
      394,  259,  302,  265,    0,    0,    0,  671,  176,  246,
      249,  225,  243,  670,  256,  669,  277,  259,  668,  255,
        0,    0,    0,    0,    0,  685,  301,    0,  444,  303,
      306,  316,    0,    0,    0,  666,  297,  304,  296,  290,
      301,  665,  308,  664,  327,  309,  663,  328,    0,  683,
      362,  701,  758,  700,  352,  367,  687,  686,  669,  663,
      663,    0,  662,  665,  660,  661,  653,    0,  646,    0,
      651,  668,  369,  494,  758,  686,  368,  374,  673,  672,

      359,  333,  364,  643,  369,  362,  371,  375,  325,  642,
      370,  641,  377,  661,  410,  544,  396,  415,  667,  639,
      392,  393,  397,  609,  398,  406,  399,  395,  412,  603,
      411,  602,  416,  611,  623,  622,  449,  621,  620,  592,
        0,    0,  587,  584,  597,  582,  577,  579,  586,  592,
      601,  600,  451,  599,  598,  426,  563,  557,  551,  349,
      427,  428,  429,  549,  433,  563,  575,  574,  466,  573,
      572,  440,  543,  542,  541,  437,  456,  441,  442,  540,
      459,  561,  566,  565,    0,  538,    0,  545,  539,  542,
      534,    0,  552,  557,  556,  527,  448,  526,  470,  401,

      471,  449,  525,  546,  551,  550,  521,  463,  520,  474,
      473,  475,  478,  519,  534,    0,  523,  517,  523,    0,
      530,  513,  372,  480,  477,  512,  527,  509,  488,  484,
      493,  506,  520,    0,  501,    0,  517,  497,  489,  496,
      514,  494,  492,  491,  503,    0,  489,  465,  441,  291,
      294,  272,  244,  239,  225,  192,  758,    0,    0,  758,
      595,  167,  603,  611,  618,  625,  633,  641,  649,  657,
      665,  673
    } ;

static yyconst flex_int16_t yy_def[373] =
    {   0,
      360,    1,  360,    3,  360,    5,    1,    1,    1,    1,
      360,  360,  360,  360,  360,  360,  361,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  362,  363,  362,  362,
      362,  362,  362,  362,  362,  360,  360,  360,  364,  360,
      360,  360,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  365,  365,   53,   53,   53,   53,   53,   53,  364,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      367,  367,   72,   72,   72,   72,   72,   72,  366,  360,
      360,  361,  368,  369,  360,  360,  360,  360,  360,  360,
      370,  360,  360,  360,  360,  360,  360,  362,  363,  362,

      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  360,  364,  360,  364,  364,  364,  364,  364,  364,
      371,  364,  364,  364,  364,  364,  364,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
      364,  366,  366,  366,  366,  366,  366,  366,  372,  366,
      366,  366,  366,  366,  366,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,  366,  360,
      360,  370,  360,  370,  360,  360,  360,  360,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  364,  364,  371,  360,  370,  364,  364,  364,  364,

       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,  366,  366,  372,  366,  366,  366,  366,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,  360,  360,  360,  360,  360,  360,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  364,
      364,  364,  364,  364,  364,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,  366,  366,  366,  366,  366,
      366,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,  360,  360,  360,  362,  362,  362,  362,  362,  362,
      362,  362,  364,  364,  364,   53,   53,   53,   53,   53,

       53,   53,   53,  366,  366,  366,   72,   72,   72,   72,
       72,   72,   72,   72,  360,  362,  362,  362,  362,  362,
      364,   53,   53,   53,   53,   53,  366,   72,   72,   72,
       72,   72,  360,  362,  362,  362,  364,   53,   53,   53,
      366,   72,   72,   72,  360,  362,  364,   53,  366,   72,
      360,  364,  366,  360,  364,  366,  360,  364,  366,    0,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360
    } ;

static yyconst flex_int16_t yy_nxt[810] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   19,   12,   20,
       12,   12,   21,   22,   23,   12,   24,   25,   26,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   28,
       27,   29,   27,   27,   30,   31,   27,   32,   27,   27,
       27,   27,   33,   34,   27,   27,   35,   27,   36,   37,
       38,   39,   40,   41,   42,   43,   17,   18,   44,   39,
       45,   39,   39,   46,   47,   48,   12,   49,   50,   51,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       28,   52,   53,   52,   52,   54,   55,   52,   56,   52,
       52,   52,   52,   57,   58,   52,   52,   59,   52,   36,

       60,   38,   61,   40,   41,   42,   62,   17,   18,   63,
       12,   64,   61,   61,   65,   66,   67,   61,   68,   69,
       70,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   28,   71,   72,   71,   71,   73,   74,   71,   75,
       71,   71,   71,   71,   76,   77,   71,   71,   78,   71,
       36,   79,   38,   83,   84,   87,   90,   92,  107,   93,
       91,  101,  102,  108,  104,  117,  105,   94,   88,  103,
      106,  120,  122,   98,  123,  121,  145,  138,  118,   94,
      130,  131,  124,  128,  133,  128,  134,  128,  132,  146,
      135,  136,  166,  148,  124,  113,  137,  149,  128,  113,

      156,  359,  113,  113,  113,  113,  113,  113,  113,  140,
      201,  113,  113,  113,  128,  128,  139,  150,  128,  151,
      158,  159,  156,  156,  167,   83,   84,  152,  160,  161,
      168,  162,  156,  164,  358,  163,  156,  180,  165,  152,
      156,  173,  174,  181,  113,  113,  177,  177,  357,  113,
      178,   89,  113,  113,  113,  113,  113,  113,  113,  171,
      175,  113,  113,  113,   92,  187,   93,  128,  176,  205,
      119,  171,  356,  197,   94,  199,  199,  188,  193,  200,
      176,  198,  204,  202,  206,  128,   94,  129,  128,  203,
      193,  128,  213,  198,  113,  142,  208,  128,  128,  142,

      355,  128,  142,  211,  142,  142,  142,  142,  142,  209,
      142,  142,  142,  142,  122,  147,  123,  217,  150,  128,
      151,  210,  354,  215,  124,  218,  219,  219,  152,  224,
      220,  221,  156,  156,  225,  215,  124,  218,  156,  156,
      152,  222,  226,  156,  142,  142,  156,  223,  228,  142,
      156,  156,  142,  231,  142,  142,  142,  142,  142,  229,
      142,  142,  142,  142,  263,  233,  175,  128,  257,  156,
      156,  230,  235,  235,  237,  128,  236,  238,  238,  251,
      251,  239,  197,  252,  254,  254,  237,  157,  255,  256,
      253,  128,  260,  298,  142,  172,  195,  196,  258,  172,

      172,  128,  253,  259,  128,  261,  128,  262,  338,  172,
      217,  128,  128,  128,  128,  264,  265,  128,  269,  128,
      267,  267,  272,  172,  268,  270,  270,  278,  273,  271,
      269,  274,  275,  277,  156,  156,  276,  156,  324,  156,
      156,  156,  172,  128,  172,  172,  195,  196,  156,  172,
      172,  279,  172,  156,  156,  281,  280,  299,  156,  283,
      283,  294,  294,  284,  296,  295,  353,  303,  128,  128,
      128,  128,  300,  172,  301,  128,  305,  305,  307,  156,
      306,  309,  156,  156,  156,  311,  310,  312,  322,  326,
      128,  128,  172,  314,  172,  172,  360,  172,  156,  172,

      172,  156,  323,  328,  325,  156,  329,  128,  331,  172,
      330,  340,  128,  128,  352,  156,  156,  156,  332,  128,
      156,  339,  128,  172,  342,  343,  156,  344,  351,  348,
      156,  128,  350,  156,  156,  156,  156,  349,  128,  128,
      347,  346,  172,  345,  172,  172,  360,  172,  156,  172,
      172,  156,  172,  341,  128,  128,  337,  336,  335,  334,
      333,  156,  156,  156,  306,  306,  327,  128,  128,  128,
      295,  295,  321,  172,  320,  319,  318,  317,  316,  284,
      284,  315,  313,  308,  156,  156,  271,  271,  268,  268,
      304,  302,  172,  297,  172,   82,   82,   82,   82,  128,

       82,   82,   82,   99,   99,  128,   99,   99,   99,   99,
       99,  113,  255,  255,  252,  252,  113,  113,  128,  293,
      292,  291,  290,  128,  128,  142,  289,  288,  287,  286,
      285,  142,  142,  156,  239,  239,  236,  236,  282,  156,
      156,   83,   83,   83,  156,  156,   83,   83,   83,   84,
       84,  156,   84,  220,   84,   84,   84,  172,  172,  172,
      172,  172,  172,  172,  172,  194,  194,  194,  194,  194,
      194,  194,  194,  216,  216,  216,  216,  216,  216,  216,
      216,  220,  266,  128,  128,  128,  200,  200,  360,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,

      178,  178,  360,  360,  234,  232,  156,  227,  156,  214,
      212,  128,  207,  128,  192,  114,  191,  190,  189,  186,
      185,  184,  183,  182,  179,  170,   85,   80,  169,  155,
      154,  153,  147,  144,  143,  141,  127,  126,  125,  119,
      116,  115,  114,  112,  111,  110,  109,  100,   97,   96,
       95,   89,   86,   85,   81,   80,  360,   11,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,

      360,  360,  360,  360,  360,  360,  360,  360,  360
    } ;

static yyconst flex_int16_t yy_chk[810] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,   17,   17,   20,   22,   23,   32,   23,
       22,   30,   30,   32,   31,   45,   31,   23,   20,   30,
       31,   47,   48,  362,   48,   47,   64,   57,   45,   23,
       54,   54,   48,   54,   55,   57,   55,   55,   54,   64,
       55,   56,   76,   66,   48,   52,   56,   66,   56,   52,

       76,  356,   52,   52,   52,   52,   52,   52,   52,   59,
      129,   52,   52,   52,   58,   59,   58,   67,  129,   67,
       73,   73,   77,   73,   77,   82,   82,   67,   73,   74,
       78,   74,   74,   75,  355,   74,   78,  101,   75,   67,
       75,   91,   91,  101,   52,   53,   94,   94,  354,   53,
       94,   89,   53,   53,   53,   53,   53,   53,   53,   89,
       92,   53,   53,   53,   93,  108,   93,  132,   92,  132,
      119,   89,  353,  122,   93,  124,  124,  108,  119,  124,
       92,  122,  131,  130,  133,  133,   93,   53,  130,  130,
      119,  131,  140,  122,   53,   71,  135,  140,  135,   71,

      352,  138,   71,  138,   71,   71,   71,   71,   71,  137,
       71,   71,   71,   71,  123,  147,  123,  150,  151,  137,
      151,  137,  351,  147,  123,  150,  152,  152,  151,  159,
      152,  157,  160,  350,  160,  147,  123,  150,  159,  157,
      151,  158,  161,  161,   71,   72,  158,  158,  163,   72,
      163,  166,   72,  166,   72,   72,   72,   72,   72,  165,
       72,   72,   72,   72,  209,  168,  175,  209,  202,  165,
      168,  165,  171,  171,  175,  202,  171,  176,  176,  193,
      193,  176,  197,  193,  198,  198,  175,   72,  198,  201,
      197,  260,  206,  260,   72,  121,  121,  121,  203,  121,

      121,  201,  197,  205,  206,  207,  203,  208,  323,  121,
      217,  205,  211,  207,  323,  211,  213,  208,  217,  213,
      215,  215,  221,  121,  215,  218,  218,  228,  222,  218,
      217,  223,  225,  227,  221,  222,  226,  228,  300,  223,
      225,  227,  121,  300,  121,  149,  149,  149,  226,  149,
      149,  229,  149,  231,  229,  233,  231,  261,  233,  237,
      237,  253,  253,  237,  256,  253,  349,  265,  256,  261,
      262,  263,  262,  149,  263,  265,  269,  269,  272,  276,
      269,  276,  272,  278,  279,  278,  277,  279,  297,  302,
      297,  302,  149,  281,  149,  194,  194,  194,  277,  194,

      194,  281,  299,  308,  301,  308,  310,  348,  312,  194,
      311,  325,  299,  301,  347,  311,  310,  312,  313,  325,
      313,  324,  324,  194,  329,  330,  330,  331,  345,  339,
      329,  339,  343,  344,  343,  331,  342,  341,  340,  338,
      337,  335,  194,  333,  194,  216,  216,  216,  332,  216,
      216,  328,  216,  327,  326,  322,  321,  319,  318,  317,
      315,  314,  309,  307,  306,  305,  304,  303,  298,  296,
      295,  294,  293,  216,  291,  290,  289,  288,  286,  284,
      283,  282,  280,  275,  274,  273,  271,  270,  268,  267,
      266,  264,  216,  259,  216,  361,  361,  361,  361,  258,

      361,  361,  361,  363,  363,  257,  363,  363,  363,  363,
      363,  364,  255,  254,  252,  251,  364,  364,  365,  250,
      249,  248,  247,  365,  365,  366,  246,  245,  244,  243,
      240,  366,  366,  367,  239,  238,  236,  235,  234,  367,
      367,  368,  368,  368,  232,  230,  368,  368,  368,  369,
      369,  224,  369,  220,  369,  369,  369,  370,  370,  370,
      370,  370,  370,  370,  370,  371,  371,  371,  371,  371,
      371,  371,  371,  372,  372,  372,  372,  372,  372,  372,
      372,  219,  214,  212,  210,  204,  200,  199,  196,  192,
      191,  189,  187,  186,  185,  184,  183,  181,  180,  179,

      178,  177,  174,  172,  170,  167,  164,  162,  156,  146,
      139,  136,  134,  128,  118,  114,  111,  110,  109,  106,
      105,  104,  103,  102,  100,   88,   85,   80,   79,   70,
       69,   68,   65,   63,   62,   60,   51,   50,   49,   46,
       44,   43,   40,   37,   35,   34,   33,   29,   26,   25,
       24,   21,   19,   18,   16,   13,   11,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,

      360,  360,  360,  360,  360,  360,  360,  360,  360
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[53] =
    {   0,
0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
++(yy_lp); \
goto find_rule; \
}

static int yy_more_offset = 0;
static int yy_prev_more_offset = 0;
#define yymore() ((yy_more_offset) = yy_flex_strlen( yytext ))
#define YY_NEED_STRLEN
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET \
	{ \
	(yy_more_offset) = (yy_prev_more_offset); \
	yyleng -= (yy_more_offset); \
	}
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "script.l"
#line 6 "script.l"
static char lexrcsid[] = "$Id: script.l,v 1.2 2006/02/15 18:47:00 svitak Exp $";

/*
** $Log: script.l,v $
** Revision 1.2  2006/02/15 18:47:00  svitak
** Changes to allow parsing of scripts which use linefeeds containing \r, or
** carriage return.
**
** Revision 1.1.1.1  2005/06/14 04:38:32  svitak
** Import from snapshot of CalTech CVS tree of June 8, 2005
**
** Revision 1.15  2001/04/25 17:17:04  mhucka
** Misc. small changes to improve portability and address compiler warnings.
**
** Revision 1.13  1999/04/24 01:42:18  mhucka
** The code for handling comments failed to work properly; it did not deal with
** oddball comments within C-style comments in .g files.  Replaced with new code
** taken from an ANSI C lex definition of the C language itself.
**
** Revision 2.1.1.1  1999/03/17 07:53:52  mhucka
** Import of GENESIS 2.1 release from CD-ROM
**
** Revision 1.12  1997/05/29 09:06:05  dhb
** Update from Antwerp GENESIS version 21e
**
 * EDS20l 1995/01/25  eds
 * Added MachTen compatibility
 *
 * Revision 1.11  1995/05/01  18:24:06  dhb
 * ifdef irix changed to ifdef sgi
 *
 * Revision 1.10  1995/04/29  01:23:00  dhb
 * Replaced lexer implementation specific code.  File is now flex and
 * bison compatible.
 *
 * Revision 1.9  1995/04/15  02:23:11  dhb
 * Empty update to force reprocessing by lex.
 *
 * Revision 1.8  1995/02/22  19:14:05  dhb
 * Linux support.
 *
 * Revision 1.7  1994/12/02  00:05:45  dhb
 * Added elif to if then else construct.
 *
 * Added ** operator to do pow().
 *
 * Fixed error in C style comments uncovered by new ** operator.
 *
 * Revision 1.6  1994/10/26  00:02:13  dhb
 * nextchar() was not reinitializing internal state properly (the cp
 * variable) when called to flush input.
 *
 * Revision 1.5  1994/09/29  20:49:36  dhb
 * C comment syntax in RCS log causing compile problems
 *
 * Revision 1.4  1994/09/23  16:38:38  dhb
 * Change to C style comment rule to fix lexing of comments on a command
 * line as a LITERAL.
 *
 * Revision 1.3  1994/04/01  19:02:00  dhb
 * nextchar() was missing extern declaration of CurrentScriptFp().
 *
 * Revision 1.2  1994/03/23  02:41:25  dhb
 * Changes to allow nextchar() to return 0 on end of file.  This allows
 * the parser to reduce the top level rule and exit the parser.  The code_g
 * program uses this capability.  GENESIS will never reach eof so no change
 * there.
 *
 * Revision 1.1  1992/12/11  21:18:51  dhb
 * Initial revision
 *
*/

#include <string.h>
#include "shell_func_ext.h"

#ifdef sgi
extern void exit();
#endif

#ifdef FLEX_SCANNER

static size_t GEN_moreinput();

#define YY_INPUT(buf,result,n)	result = GEN_moreinput(buf, n)

#else

#undef input
#define input() (((yytchar=yysptr>yysbuf?U(*--yysptr):nextchar(0))==10?(yylineno++,yytchar):yytchar)==EOF?0:yytchar)

    /* YY_START - return current BEGIN state as value usable with BEGIN */
#define	YY_START	(yybgin-yysvec - 1)
#define	YY_NULL		0

#endif

extern int yyerror();

/* Forward declarations */
static void Ccomment();
static void Pushyybgin();
static void Popyybgin();

#ifdef LEXTEST
#    define	lextoken(tok)	printf("%s ==> %s\n", yytext, "tok")
#    define	lexchar(ch)	printf("'%c'\n", ch)
#else
#  ifdef YACCTEST
#    define	lextoken(tok)	{ printf("%s ==> %s\n", yytext, "tok"); return(tok); }
#    define	lexchar(ch)	{ printf("'%c'\n", ch); return(ch); }
#  else
#    define	lextoken(tok)	return(tok)
#    define	lexchar(ch)	return(ch)
#  endif
#endif

#define	BGINSTKSIZE	100

static int	yybginstk[BGINSTKSIZE];
static int	yybginidx = 0;
static int	continuation = 0;
/*
** C comment handling taken from ANSI C Lex specification published by
** Jeff Lee and Jutta Degener <jutta@pobox.com>.
*/

#line 141 "script.l"
/* I use this area to hold things that I might want back */

#ifdef COMMENT
<CPPCOMMENT>[^\n]*	Popyybgin();
"//"			Pushyybgin(CPPCOMMENT);

\\\n			continuation = 0;

<CCOMMENT>[^*\n]*	;
<CCOMMENT>"*"		;
<CCOMMENT>"\n"		;
<CCOMMENT>"*/"		Popyybgin();
"/*"/[^\n]*		Pushyybgin(CCOMMENT);
#endif
#line 1022 "lex.yy.c"

#define INITIAL 0
#define LIT 1
#define FUNCLIT 2
#define CCOMMENT 3
#define CPPCOMMENT 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 157 "script.l"


#line 1216 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 361 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 758 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
					{
					(yy_full_match) = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = (yy_prev_more_offset); yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 159 "script.l"
Ccomment();
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 161 "script.l"
;
	YY_BREAK
case 3:
/* rule 3 can match eol */
#line 164 "script.l"
case 4:
/* rule 4 can match eol */
#line 165 "script.l"
case 5:
/* rule 5 can match eol */
#line 166 "script.l"
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 166 "script.l"
{
			  if (!continuation)
			      lexchar('\n');
			  else
			    {
			      continuation = 0;
			      lexchar(WHITESPACE);
			    }
			}
	YY_BREAK
case 7:
#line 177 "script.l"
case 8:
/* rule 8 can match eol */
#line 178 "script.l"
case 9:
/* rule 9 can match eol */
#line 179 "script.l"
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 179 "script.l"
{
			  if (!continuation)
			      lexchar('\n');

			  continuation = 0;
			}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 186 "script.l"
continuation = 1;
	YY_BREAK
case 12:
#line 189 "script.l"
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 189 "script.l"
{
			  char	ch;

			  ch = (char)input();
			  if (ch == '\n')
			    {
			      yyerror
			      ("Missing closing quote in string constant");
			      /* No Return */
			    }

			  if (ch == '\r')
			    {
			      yyerror
			      ("Missing closing quote in string constant");
			      /* No Return */
			    }

			  if (yytext[yyleng-1] == '\\')
			    {
			      yytext[yyleng-1] = '"';
			      yyless(yyleng-1);
			      yymore();
			    }
			  else
			    {
			      yylval.str = (char *) strsave(yytext+1);
			      lextoken(STRCONST);
			    }
			};
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 220 "script.l"
{
			  sscanf(yytext+1, " %d ", &yylval.iconst);
			  lextoken(DOLLARARG);
			}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 225 "script.l"
{ 
			  yylval.str = (char *) strsave(yytext);
			  lextoken(LITERAL);
			};
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 230 "script.l"
{ 
			  yylval.str = (char *) strsave(yytext);
			  lextoken(LITERAL);
			};
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 235 "script.l"
lextoken(WHITESPACE);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 236 "script.l"
;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 238 "script.l"
lextoken(INCLUDE);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 240 "script.l"
lextoken(ENDSCRIPT);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 242 "script.l"
lextoken(BREAK);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 244 "script.l"
lextoken(RETURN);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 246 "script.l"
lextoken(WHILE);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 248 "script.l"
lextoken(IF);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 250 "script.l"
lextoken(ELSE);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 252 "script.l"
lextoken(ELIF);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 254 "script.l"
lextoken(FOR);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 256 "script.l"
lextoken(FOREACH);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 258 "script.l"
lextoken(END);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 260 "script.l"
lextoken(FUNCTION);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 262 "script.l"
lextoken(EXTERN);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 264 "script.l"
lextoken(INT);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 266 "script.l"
lextoken(FLOAT);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 268 "script.l"
lextoken(STR);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 270 "script.l"
lextoken(LT);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 271 "script.l"
lextoken(LE);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 272 "script.l"
lextoken(GT);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 273 "script.l"
lextoken(GE);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 274 "script.l"
lextoken(EQ);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 275 "script.l"
lextoken(NE);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 277 "script.l"
lextoken(OR);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 278 "script.l"
lextoken(AND);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 280 "script.l"
lextoken(POW);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 282 "script.l"
{
			  Result	*rp;

			  if (!ReturnIdents &&
			      ((rp=SymtabLook(LocalSymbols, yytext)) != NULL ||
			       (rp=SymtabLook(&GlobalSymbols, yytext)) != NULL))
			    {
			      yylval.str = (char *) rp;
			      if (rp->r_type == FUNCTION)
				  { lextoken(FUNCREF); }
			      else
				  lextoken(VARREF);
			    }
			  else
			    {
			      yylval.str = (char *) strsave(yytext);
			      lextoken(IDENT);
			    }
			};
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 302 "script.l"
{
			  sscanf(yytext, " %d ", &yylval.iconst);
			  lextoken(INTCONST);
			}
	YY_BREAK
case 46:
#line 308 "script.l"
case 47:
#line 309 "script.l"
case 48:
YY_RULE_SETUP
#line 309 "script.l"
{
			  sscanf(yytext, " %lf ", &yylval.fconst);
			  lextoken(FLOATCONST);
			}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 314 "script.l"
{ Pushyybgin(0); lexchar('{'); };
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 315 "script.l"
{ Popyybgin(); lexchar('}'); };
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 317 "script.l"
lexchar(yytext[0]);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 318 "script.l"
ECHO;
	YY_BREAK
#line 1634 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(LIT):
			case YY_STATE_EOF(FUNCLIT):
			case YY_STATE_EOF(CCOMMENT):
			case YY_STATE_EOF(CPPCOMMENT):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 361 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 361 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 360);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 318 "script.l"



/*
** Routine to handle C comments.
*/

static void Ccomment()
{
        char c, c1;

loop:
        while ((c = (char)input()) != '*' && c != 0)
                ;

        if ((c1 = (char)input()) != '/' && c != 0)
	{
		unput(c1);
                goto loop;
	}
}

/*
** Lexer routines to push and pop the lexer begin state
*/

static void Pushyybgin(start)

int	start;

{	/* Pushyybgin --- Push to another lexer begin state */

	if (yybginidx == BGINSTKSIZE)
	    yyerror("Pushyybgin: lexer begin state stack overflow");
	    /* No Return */

	yybginstk[yybginidx++] = YY_START;
	BEGIN start;

}	/* Pushyybgin */



static void Popyybgin()

{	/* Popyybgin --- Pop to previous lexer begin state */

	if (yybginidx == 0)
	    yyerror("Popyybgin: lexer begin state stack underflow");
	    /* No Return */

	BEGIN yybginstk[--yybginidx];

}	/* Popyybgin */



/*
** Local routine to get input characters
**
** For FLEX_SCANNER we don't need to do this buffering since
** flex does it for us.  We still provide nextchar() as a method
** for flushing the lexer input.  The *END SCRIPT* stuff will be
** handled in the YY_INPUT macro.
*/

static size_t GEN_moreinput(buf, n)

char*	buf;
int	n;

{
	extern FILE* CurrentScriptFp();

	char*	cp;
	size_t	result;

	do
	  {
	    cp = (char *) sgets(buf, n);
	  }
       while (cp != NULL && *cp == '\0');

	if (cp == NULL)
	  {
	    if (feof(CurrentScriptFp()))
		result = YY_NULL; /* END OF INPUT */
	    else
	      {
		sprintf(buf, "*ENDSCRIPT*\n");
		result = strlen(buf);
	      }
	  }
	else
	    result = strlen(buf);

	return result;

}

#ifdef FLEX_SCANNER

int nextchar(flush)

int	flush;

{
	if (flush)
	  {
	    yybginidx = 0;
	    BEGIN 0;
	    yyrestart(yyin); /* flushes flex input buffer */
	  }

	return 0;
}

#else
int nextchar(flush)

int	flush;

{	/* nextchar --- Return next char to lexer */

	static char	buf[100] = "";
	static char	*cp = buf;

	if (flush)
	  {
	    yybginidx = 0;
	    BEGIN 0;
	    yysptr = yysbuf;
	    cp = buf;
	    *cp = '\0';
	    return 0;
	  }

	if (cp == NULL)
	    return 0;

	if (*cp != '\0')
	    return *cp++;

	if (GEN_moreinput(buf, sizeof(buf)) == 0)
	  {
	    cp = NULL;
	    return 0;
	  }

	cp = buf;
	return(*cp++);

}	/* nextchar */
#endif

/*
** For systems that don't have a lex library, we define some of the support
** routines.
*/

/* mds3 changes */
#if defined(i860)
yyless(x)
{
extern char yytext[];
register char *lastch, *ptr;
extern int yyleng;
extern int yyprevious;
lastch = yytext+yyleng;
if (x>=0 && x <= yyleng)
        ptr = x + yytext;
else
        ptr = x;
while (lastch > ptr)
        yyunput(*--lastch);
*lastch = 0;
if (ptr >yytext)
        yyprevious = *--lastch;
yyleng = ptr-yytext;
}
#endif
 
#if defined(i860) || defined(machten)
yywrap()
{
return 1;
}
#endif
/* end of mds3 changes */

